### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by ghost** [nbering/terraform-inventory#7]
Are you considering to upstream this as an [inventory plugin](https://docs.ansible.com/ansible/latest/plugins/inventory.html#inventory-plugins) into Ansible, so that it is available to every user of Ansible right from the start?

**Comment by nbering** [comment]
No, I have no intention of upstreaming this because the plugin it supports isn't mainstream on the Terraform side, and the way the ecosystem works right now there's little prospect of that.

**Comment by nbering** [comment]
As for the plugin potential, that was addressed some time ago in #3, but I may look into making the switch if the support for inventory plugins has improved.

**Comment by nbering** [comment]
Doing some issue cleanup. My view on this hasn't really changed, so I'm going to close.

It's not that I wouldn't want it included in upstream, I just don't consider it practical to ask the Ansible team to commit to long-term maintenance of my little hacked-together script that services a rather small audience. If the audience grows or the [terraform provider](https://github.com/nbering/terraform-provider-ansible) is adopted into the terraform-providers organization, it'd certainly put some weight behind committing upstream.
